devicemap = {
    'a5': 'HTC Desire 816',
    'a700': 'Acer Iconia Tab A700',
    'acclaim': 'Barnes & Noble Nook Tablet',
    'ace': 'HTC Desire HD / Inspire 4G',
    'amami': 'Sony Xperia Z1 Compact',
    'anzu': 'Sony Ericsson Xperia Arc',
    'aoba': 'Sony Xperia ion',
    'apexqtmo': 'Samsung Galaxy S Relay 4G',
    'aries': 'Xiaomi Mi2',
    'asanti': 'Motorola Photon Q',
    'bacon': 'OnePlus One',
    'betelgeuse': 'Toshiba Folio 100',
    'blade': 'ZTE Blade',
    'bravo': 'HTC Desire (GSM)',
    'bravoc': 'HTC Desire (CDMA)',
    'buzz': 'HTC Wildfire',
    'c660': 'LG Optimus Pro',
    'c800': 'LG myTouch Q',
    'cancro': 'Xiaomi Mi3w and Mi4',
    'captivatemtd': 'Samsung Captivate',
    'castor': 'Sony Xperia Z2 Tablet (LTE)',
    'castor_windy': 'Sony Xperia Z2 Tablet (Wi-Fi)',
    'cdma_droid2we': 'Motorola Droid 2 World Edition (CDMA)',
    'click': 'HTC Tattoo',
    'coconut': 'Sony Ericsson Live with Walkman',
    'condor': 'Motorola E',
    'cooper': 'Samsung Galaxy Ace',
    'crespo': 'Google Nexus S',
    'crespo4g': 'Google Nexus S 4G',
    'd2att': 'Samsung Galaxy S III (AT&T)',
    'd2cri': 'Samsung Galaxy S III (Cricket)',
    'd2lte': 'Samsung Galaxy S III (US)',
    'd2mtr': 'Samsung Galaxy S III (MetroPCS)',
    'd2spr': 'Samsung Galaxy S III (Sprint)',
    'd2tmo': 'Samsung Galaxy S III (T-Mobile)',
    'd2usc': 'Samsung Galaxy S III (US Cellular)',
    'd2vzw': 'Samsung Galaxy S III (Verizon)',
    'd710': 'Samsung Galaxy S II Epic Touch 4G',
    'd800': 'LG G2 (AT&T)',
    'd801': 'LG G2 (T-Mobile)',
    'd802': 'LG G2 (Intl)',
    'd803': 'LG G2 (Canada)',
    'd850': 'LG G3 (AT&T)',
    'd851': 'LG G3 (T-Mobile)',
    'd852': 'LG G3 (Canada)',
    'd855': 'LG G3 (Unlocked)',
    'deb': 'Google Nexus 7 2013 (4G)',
    'desirec': 'Droid Eris',
    'dlx': 'HTC Droid DNA',
    'dlxj': 'HTC J Butterfly',
    'dlxu': 'HTC Butterfly',
    'dogo': 'Sony Xperia ZR',
    'doubleshot': 'T-Mobile myTouch 4G Slide',
    'dream_sapphire': 'HTC Dream / Magic',
    'droid2': 'Motorola Droid 2',
    'droid2we': 'Motorola Droid 2 Global',
    'e400': 'LG Optimus L3',
    'e510': 'LG Optimus Hub',
    'e610': 'LG Optimus L5',
    'e720': 'LG Optimus Chic',
    'e730': 'LG Optimus Sol',
    'e739': 'LG myTouch',
    'e970': 'LG Optimus G (AT&T)',
    'e973': 'LG Optimus G (Canada)',
    'e975': 'LG Optimus G (Intl)',
    'e980': 'LG Optimus G Pro (All e98x GSM)',
    'e986': 'Replaced with e980',
    'edison': 'Motorola Atrix 2',
    'encore': 'Barnes & Noble Nook Color',
    'endeavoru': 'HTC One X',
    'enrc2b': 'HTC One X+',
    'epicmtd': 'Samsung Epic 4G',
    'es209ra': 'Sony Ericsson Xperia X10',
    'espresso': 'T-Mobile myTouch 3G Slide',
    'everest': 'Motorola Xoom (GSM)',
    'evita': 'HTC One XL',
    'exhilarate': 'Samsung Galaxy Exhilarate',
    'expressatt': 'Samsung Galaxy Express (AT&T)',
    'falcon': 'Motorola Moto G',
    'fascinatemtd': 'Samsung Fascinate',
    'find5': 'Oppo Find 5',
    'find7': 'Oppo Find 7a',
    'find7s': 'Oppo Find 7s',
    'fireball': 'Droid Incredible 4G LTE',
    'flo': 'Google Nexus 7 2013 (Wi-Fi)',
    'flounder': 'Google Nexus 9',
    'fugu': 'Google Nexus Player',
    'gaga': 'Sony Xperia UL',
    'galaxys2': 'Samsung Galaxy S II (Intl)',
    'galaxys2att': 'Samsung Galaxy S II (AT&T)',
    'galaxysbmtd': 'Samsung Galaxy S (B)',
    'galaxysmtd': 'Samsung Galaxy S',
    'ghost': 'Motorola Moto X (2013)',
    'glacier': 'T-Mobile myTouch 4G',
    'golden': 'Samsung Galaxy S III Mini',
    'grouper': 'Google Nexus 7 (Wi-Fi)',
    'haida': 'Sony Ericsson Xperia Neo V',
    'hallon': 'Sony Ericsson Xperia Neo',
    'hammerhead': 'Google Nexus 5',
    'hammerheadcaf': 'Google Nexus 5 (CAF)',
    'harmony': 'ViewSonic G Tablet',
    'hayabusa': 'Sony Xperia TX',
    'hercules': 'Samsung Galaxy S II (T-Mobile)',
    'hero': 'HTC Hero (GSM)',
    'heroc': 'HTC Hero (CDMA)',
    'hikari': 'Sony Xperia arco S',
    'hlte': 'Samsung Galaxy Note 3 (Unified)',
    'hltespr': 'Samsung Galaxy Note 3 (Sprint)',
    'hltetmo': 'Samsung Galaxy Note 3 (T-Mobile)',
    'hlteusc': 'Samsung Galaxy Note 3 (US-Cellular)',
    'hltevzw': 'Samsung Galaxy note 3 (Verizon)',
    'hltexx': 'Samsung Galaxy Note 3 (Intl)',
    'holiday': 'HTC Raider 4G',
    'honami': 'Sony Xperia Z1',
    'huashan': 'Sony Xperia SP',
    'hummingbird': 'Barnes & Noble Nook HD',
    'i605': 'Samsung Galaxy Note II (Verizon)',
    'i777': 'Samsung Galaxy S II (AT&T)',
    'i9100': 'Samsung Galaxy S II (Intl)',
    'i9100g': 'Samsung Galaxy S II (G)',
    'i9103': 'Samsung Galaxy R',
    'i925': 'Samsung Galaxy Note 10.1 (Verizon)',
    'i9300': 'Samsung Galaxy S III (Intl)',
    'i9305': 'Samsung Galaxy S III (GSM LTE)',
    'i9500': 'Samsung Galaxy S4 (non-LTE)',
    'inc': 'Droid Incredible',
    'iyokan': 'Sony Ericsson Xperia Pro',
    'ja3g': 'Samsung Galaxy S4 (GSM Non-LTE)',
    'jactivelte': 'Samsung Galaxy S4 Active (intl)',
    'jem': 'Amazon Kindle Fire HD 8.9"',
    'jewel': 'HTC Evo 4G LTE',
    'jflte': 'Samsung Galaxy S4',
    'jflteatt': 'Samsung Galaxy S4 (AT&T)',
    'jfltecan': 'Samsung Galaxy S4 (Canada)',
    'jfltecri': 'Samsung Galaxy S4 (Cricket)',
    'jfltecsp': 'Samsung Galaxy S4 (C Spire)',
    'jfltespr': 'Samsung Galaxy S4 (Sprint)',
    'jfltetmo': 'Samsung Galaxy S4 (T-Mobile)',
    'jflteusc': 'Samsung Galaxy S4 (US Cellular)',
    'jfltevzw': 'Samsung Galaxy S4 (Verizon)',
    'jfltexx': 'Samsung Galaxy S4 (Intl)',
    'jlo': 'Sony Xperia J',
    'jordan': 'Motorola Defy',
    'jordan_plus': 'Motorola Defy+',
    'klimtwifi': 'Samsung Galaxy Tab S 8.4 (Wifi)',
    'klte': 'Samsung Galaxy S5',
    'kltechn': 'Samsung Galaxy S5 (China)',
    'kltechnduo': 'Samsung Galaxy S5 Duos (China)',
    'klteduos': 'Samsung Galaxy S5 Duos',
    'kltedv': 'Samsung Galaxy S5 (Vodafone)',
    'kltekdi': 'Samsung Galaxy S5 (AU)',
    'kltespr': 'Samsung Galaxy S5 (Sprint)',
    'klteusc': 'Samsung Galaxy S5 (US Cellular)',
    'kltevzw': 'Samsung Galaxy S5 (Verizon)',
    'ks01lte': 'Samsung Galaxy S4',
    'l01f': 'LG G2 (Docomo)',
    'l900': 'Samsung Galaxy Note II (Sprint)',
    'legend': 'HTC Legend',
    'lettuce': 'YU Yuphoria',
    'liberty': 'HTC Aria',
    'ls970': 'LG Optimus G (Sprint)',
    'ls980': 'LG G2 (Sprint)',
    'ls990': 'LG G3 (Sprint)',
    'm4': 'HTC One Mini',
    'm7': 'HTC One (GSM)',
    'm7att': 'HTC One (AT&T)',
    'm7spr': 'HTC One (Sprint)',
    'm7tmo': 'HTC One (T-Mobile)',
    'm7ul': 'HTC One (GSM)',
    'm7vzw': 'HTC One (Verizon)',
    'm8': 'HTC One (2014)',
    'maguro': 'Google Galaxy Nexus (GSM)',
    'mako': 'Google Nexus 4',
    'mango': 'Sony Ericsson Xperia Mini Pro',
    'manta': 'Google Nexus 10',
    'maserati': 'Motorola Droid 4',
    'mb886': 'Motorola Atrix HD',
    'memul': 'HTC One Mini 2',
    'mesmerizemtd': 'Samsung Mesmerize',
    'mesona': 'Sony Xperia miro',
    'mimmi': 'Sony Ericsson Xperia X10 Mini Pro',
    'mint': 'Sony Xperia T',
    'mondrianwifi': 'Samsung Galaxy Tab Pro 8.4',
    'morrison': 'Motorola Cliq',
    'moto_msm8960': 'Motorola MSM8960 Base',
    'moto_msm8960_jbbl': 'Motorola MSM8960 JB Bootloader',
    'moto_msm8960dt': 'Motorola X (Deprecated)',
    'motus': 'Motorola Backflip',
    'mystul': 'HTC First',
    'n1': 'Oppo N1',
    'n3': 'Oppo N3',
    'n5100': 'Samsung Galaxy Note 8.0 (GSM)',
    'n5110': 'Samsung Galaxy Note 8.0 (Wi-Fi)',
    'n5120': 'Samsung Galaxy Note 8.0 (LTE)',
    'n7000': 'Samsung Galaxy Note (Intl)',
    'n7100': 'Samsung Galaxy Note II (GSM Non-LTE)',
    'n8000': 'Samsung Galaxy Note 10.1 (GSM)',
    'n8013': 'Samsung Galaxy Note 10.1 (Wi-Fi)',
    'nanhu': 'Sony Xperia E',
    'nicki': 'Sony Xperia M',
    'nozomi': 'Sony Xperia S',
    'obake': 'Motorola Droid Ultra/MAXX',
    'odin': 'Sony Xperia ZL',
    'odroidu2': 'Hardkernel ODROID-U2',
    'olympus': 'Motorola Atrix 4G',
    'one': 'Geeksphone One',
    'otter': 'Amazon Kindle Fire (1st gen)',
    'otter2': 'Amazon Kindle Fire (2nd gen)',
    'otterx': 'Amazon Kindle Fire (1Gen, custom bl)',
    'ovation': 'Barnes & Noble Nook HD+',
    'p1': 'Samsung Galaxy Tab (GSM)',
    'p1c': 'Samsung Galaxy Tab (CDMA)',
    'p1l': 'Samsung Galaxy Tab (P1000L)',
    'p1n': 'Samsung Galaxy Tab (P1000N)',
    'p3': 'Samsung Galaxy Tab 10.1v',
    'p3100': 'Samsung Galaxy Tab 2 7.0 (GSM)',
    'p3110': 'Samsung Galaxy Tab 2 7.0 (Wi-Fi)',
    'p3113': 'Samsung Galaxy Tab 2 7.0 (Wi-Fi+IR)',
    'p350': 'LG Optimus Me',
    'p4': 'Samsung Galaxy Tab 10.1 (GSM)',
    'p4tmo': 'Samsung Galaxy Tab 10.1 (T-Mobile)',
    'p4vzw': 'Samsung Galaxy Tab 10.1 (Verizon)',
    'p4wifi': 'Samsung Galaxy Tab 10.1 (Wi-Fi)',
    'p5': 'Samsung Galaxy Tab 8.9 (GSM)',
    'p500': 'LG Optimus One',
    'p5100': 'Samsung Galaxy Tab2 10.1 (GSM)',
    'p5110': 'Samsung Galaxy Tab2 10.1 (Wi-Fi)',
    'p5113': 'Samsung Galaxy Tab2 10.1 (Wi-Fi+IR)',
    'p5wifi': 'Samsung Galaxy Tab 8.9 (Wi-Fi)',
    'p700': 'LG Optimus L7',
    'p720': 'LG Optimus 3D Max',
    'p760': 'LG Optimus L9',
    'p880': 'LG Optimus 4X HD',
    'p920': 'LG Optimus 3D',
    'p925': 'LG Thrill 4G',
    'p930': 'LG Nitro HD / Optimus LTE',
    'p940': 'LG Prada 3.0',
    'p970': 'LG Optimus Black',
    'p990': 'LG Optimus 2X',
    'p999': 'T-Mobile G2x',
    'passion': 'Google Nexus One',
    'peregrine': 'Motorola Moto G 4G',
    'picassowifi': 'Samsung Galaxy Tab Pro 10.1 (Wi-Fi)',
    'pollux': 'Sony Xperia Tablet Z',
    'pollux_windy': 'Sony Xperia Tablet Z (Wi-Fi)',
    'pyramid': 'HTC Sensation',
    'qinara': 'Motorola Atrix HD',
    'quark': 'Motorola Moto MAXX',
    'quincyatt': 'Samsung Galaxy Note (AT&T)',
    'quincytmo': 'Samsung Galaxy Note (T-Mobile)',
    'r950': 'Samsung Galaxy Note II (US Cellular)',
    'rendang': 'Smartfren Andromax Q',
    'robyn': 'Sony Ericsson Xperia X10 Mini',
    'ruby': 'HTC Amaze 4G',
    's5670': 'Samsung Galaxy Fit',
    'saga': 'HTC Desire S',
    'satsuma': 'Sony Ericsson Xperia Active',
    'scorpion': 'Sony Xperia Z3 Tablet Compact (LTE)',
    'scorpion_mini': 'Motorola Droid Razr M',
    'scorpion_windy': 'Sony Xperia Z3 Tablet Compact (Wi-Fi)',
    'serrano3gxx': 'Samsung Galaxy S4 Mini (3G)',
    'serranoltexx': 'Samsung Galaxy S4 Mini (Intl)',
    'shadow': 'Motorola Droid X',
    'shakira': 'Sony Ericsson Xperia X8',
    'shamu': 'Google Nexus 6',
    'sholes': 'Motorola Droid',
    'shooteru': 'HTC Evo 3D (GSM)',
    'showcasemtd': 'Samsung Showcase',
    'sirius': 'Sony Xperia Z2',
    'skate': 'ZTE Skate',
    'skyrocket': 'Samsung Galaxy S II Skyrocket',
    'smb_a1002': 'ViewSonic G Tablet',
    'smultron': 'Sony Ericsson Xperia Mini',
    'solana': 'Motorola Droid 3',
    'speedy': 'HTC Evo Shift',
    'sprout': 'Google Android One',
    'sprout4': 'Google Android One',
    'sprout8': 'Google Android One',
    'spyder': 'Motorola Droid Razr',
    'steelhead': 'Google Nexus Q',
    'stingray': 'Motorola Xoom (Verizon)',
    'su640': 'LG Optimus LTE (SK Telecom)',
    'sunfire': 'Motorola Photon',
    'superior': 'Samsung Galaxy Premier',
    'supersonic': 'HTC Evo 4G',
    't0lte': 'Samsung Galaxy Note II (GSM LTE)',
    't0lteatt': 'Samsung Galaxy Note II (AT&T)',
    't0ltetmo': 'Samsung Galaxy Note II (T-Mobile)',
    't6': 'HTC One Max',
    't6spr': 'HTC One Max (Sprint)',
    't6vzw': 'HTC One Max (Verizon)',
    't769': 'Samsung Galaxy S Blaze 4G',
    'taoshan': 'Sony Xperia L',
    'tapioca': 'Sony Xperia Tipo',
    'targa': 'Motorola Droid Bionic',
    'tass': 'Samsung Galaxy Mini',
    'tate': 'Amazon Kindle Fire HD 7"',
    'tenderloin': 'HP Touchpad',
    'tf101': 'Asus Eee Pad Transformer',
    'tf201': 'Asus Eee Pad Transformer Prime',
    'tf300t': 'Asus Transformer Pad TF300T',
    'tf700t': 'Asus Transformer Pad Infinity',
    'tf701t': 'Asus Transformer Pad TF701T',
    'thea': 'Motorola Moto G 4G (2014)',
    'tianchi': 'Sony Xperia T2 Ultra',
    'tilapia': 'Google Nexus 7 (GSM)',
    'titan': 'Motorola Moto G (2014)',
    'togari': 'Sony Xperia Z Ultra',
    'togari_gpe': 'Sony Xperia Z Ultra (GPE)',
    'tomato': 'YU Yureka',
    'toro': 'Google Galaxy Nexus (Verizon)',
    'toroplus': 'Google Galaxy Nexus (Sprint)',
    'trltespr': 'Samsung Galaxy Note 4 (Sprint)',
    'trltetmo': 'Samsung Galaxy Note 4 (T-Mobile)',
    'trlteusc': 'Samsung Galaxy Note 4 (US Cellular)',
    'trltexx': 'Samsung Galaxy Note 4 (Intl)',
    'tsubasa': 'Sony Xperia V',
    'u8150': 'Huawei U8150',
    'u8160': 'Huawei U8160',
    'u8220': 'Huawei U8220',
    'umts_spyder': 'Motorola Razr',
    'urushi': 'Sony Ericsson Xperia Ray',
    'v400': 'LG G Pad 7',
    'v410': 'LG G Pad 7 LTE',
    'v500': 'LG G-Pad 8.3',
    'v9': 'ZTE V9',
    'vanquish': 'Motorola Droid Razr HD',
    'vega': 'Advent Vega',
    'vibrantmtd': 'Samsung Vibrant',
    'victara': 'Motorola X (2014)',
    'vigor': 'HTC Rezound',
    'ville': 'HTC One S',
    'villec2': 'HTC One S (S3)',
    'vision': 'T-Mobile G2 / HTC Desire Z',
    'vivo': 'Droid Incredible S',
    'vivow': 'HTC Incredible 2',
    'vs920': 'LG Spectrum',
    'vs980': 'LG G2 (Verizon)',
    'vs985': 'LG G3 (Verizon)',
    'w7': 'LG Optimus L90',
    'wingray': 'Motorola Xoom (Wi-Fi)',
    'xt1053': 'Motorola X T-Mobile (2013)',
    'xt1058': 'Motorola X AT&T (2013)',
    'xt1060': 'Motorola X Developer Edition (2013)',
    'xt897': 'Motorola Photon Q',
    'xt897c': 'Motorola Photon Q (CDMA)',
    'xt907': 'Motorola Droid RAZR M',
    'xt925': 'Motorola Droid RAZR HD (GSM)',
    'xt925_jbbl': 'Motorola Droid RAZR HD JB Bootloader (GSM)',
    'xt926': 'Motorola Droid RAZR HD (CDMA)',
    'ypg1': 'Samsung Galaxy Player 4.0',
    'yuga': 'Sony Xperia Z',
    'z3': 'Sony Xperia Z3',
    'z3c': 'Sony Xperia Z3 Compact',
    'z71': 'Commtiva Z71',
    'zeppelin': 'Motorola Cliq XT',
    'zero': 'Geeksphone Zero',
    'zeus': 'Sony Ericsson Xperia Play (GSM)',
    'zeusc': 'Sony Ericsson Xperia Play (CDMA)',
}
